version: "3.5"

services:
  backend-example:
    image: backend-example-docker-img
    build: ./backend
    ports:
      - 3001:8000
    environment:
      - FRONT_URL=http://localhost:3000

  frontend-example:
    image: frontend-example-docker-img
    build: ./frontend
    ports:
      - 3000:5000
    environment:
      - API_URL=http://localhost:3001
