version: "3.5"

services:
  redis-db:
    image: redis
    ports:
      - 6379
  backend-example:
    image: backend-example-docker-img
    build: ./backend
    environment:
      - FRONT_URL=http://localhost:3000
      - REDIS=redis-db
      - REDIS_PORT=6379
      - DB_USERNAME=user
      - DB_PASSWORD=example
      - DB_NAME=postgres
      - DB_HOST=db

    depends_on:
      - redis-db
      - db

  frontend-example:
    image: frontend-example-docker-img
    build: ./frontend
    environment:
      - API_URL=http://localhost:3001
    depends_on:
      - backend-example
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - frontend-example
      - backend-example
